/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DriverFoundRouteImport } from './routes/driver-found'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowPickupRouteImport } from './routes/flow.pickup'
import { Route as FlowNegotiateRouteImport } from './routes/flow.negotiate'
import { Route as FlowEstimateRouteImport } from './routes/flow.estimate'
import { Route as FlowDestinationRouteImport } from './routes/flow.destination'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverFoundRoute = DriverFoundRouteImport.update({
  id: '/driver-found',
  path: '/driver-found',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowPickupRoute = FlowPickupRouteImport.update({
  id: '/flow/pickup',
  path: '/flow/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowNegotiateRoute = FlowNegotiateRouteImport.update({
  id: '/flow/negotiate',
  path: '/flow/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowEstimateRoute = FlowEstimateRouteImport.update({
  id: '/flow/estimate',
  path: '/flow/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowDestinationRoute = FlowDestinationRouteImport.update({
  id: '/flow/destination',
  path: '/flow/destination',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/tracking': typeof TrackingRoute
  '/flow/destination': typeof FlowDestinationRoute
  '/flow/estimate': typeof FlowEstimateRoute
  '/flow/negotiate': typeof FlowNegotiateRoute
  '/flow/pickup': typeof FlowPickupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/tracking': typeof TrackingRoute
  '/flow/destination': typeof FlowDestinationRoute
  '/flow/estimate': typeof FlowEstimateRoute
  '/flow/negotiate': typeof FlowNegotiateRoute
  '/flow/pickup': typeof FlowPickupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/tracking': typeof TrackingRoute
  '/flow/destination': typeof FlowDestinationRoute
  '/flow/estimate': typeof FlowEstimateRoute
  '/flow/negotiate': typeof FlowNegotiateRoute
  '/flow/pickup': typeof FlowPickupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/payment'
    | '/profile'
    | '/tracking'
    | '/flow/destination'
    | '/flow/estimate'
    | '/flow/negotiate'
    | '/flow/pickup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/payment'
    | '/profile'
    | '/tracking'
    | '/flow/destination'
    | '/flow/estimate'
    | '/flow/negotiate'
    | '/flow/pickup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/payment'
    | '/profile'
    | '/tracking'
    | '/flow/destination'
    | '/flow/estimate'
    | '/flow/negotiate'
    | '/flow/pickup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  CompletedRoute: typeof CompletedRoute
  DriverFoundRoute: typeof DriverFoundRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  TrackingRoute: typeof TrackingRoute
  FlowDestinationRoute: typeof FlowDestinationRoute
  FlowEstimateRoute: typeof FlowEstimateRoute
  FlowNegotiateRoute: typeof FlowNegotiateRoute
  FlowPickupRoute: typeof FlowPickupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-found': {
      id: '/driver-found'
      path: '/driver-found'
      fullPath: '/driver-found'
      preLoaderRoute: typeof DriverFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/pickup': {
      id: '/flow/pickup'
      path: '/flow/pickup'
      fullPath: '/flow/pickup'
      preLoaderRoute: typeof FlowPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/negotiate': {
      id: '/flow/negotiate'
      path: '/flow/negotiate'
      fullPath: '/flow/negotiate'
      preLoaderRoute: typeof FlowNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/estimate': {
      id: '/flow/estimate'
      path: '/flow/estimate'
      fullPath: '/flow/estimate'
      preLoaderRoute: typeof FlowEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/destination': {
      id: '/flow/destination'
      path: '/flow/destination'
      fullPath: '/flow/destination'
      preLoaderRoute: typeof FlowDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  CompletedRoute: CompletedRoute,
  DriverFoundRoute: DriverFoundRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  TrackingRoute: TrackingRoute,
  FlowDestinationRoute: FlowDestinationRoute,
  FlowEstimateRoute: FlowEstimateRoute,
  FlowNegotiateRoute: FlowNegotiateRoute,
  FlowPickupRoute: FlowPickupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
